### ISSUE TITLE
Installation seems incompatible with python 3.9+

### ISSUE THREAD

**Issue by mfiers** [BGIResearch/stereopy#11]
When I `pip install stereopy` using pytthon 3.8.10 there are no problems. However, I run into an error trying to do this with python 3.9.5:

    pip install stereopy

```
...
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
    Running setup.py install for pynndescent ... error
    ERROR: Command errored out with exit status 1:
     command: /home/mf/.pyenv/versions/3.9.5/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hkvk21ac/pynndescent_580104e55fcd428a8187c7566ef5b0a0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hkvk21ac/pynndescent_580104e55fcd428a8187c7566ef5b0a0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nsj8ft48/install-record.txt --single-version-externally-managed --compile --install-headers /home/mf/.pyenv/versions/3.9.5/include/python3.9/pynndescent
         cwd: /tmp/pip-install-hkvk21ac/pynndescent_580104e55fcd428a8187c7566ef5b0a0/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mf/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/mf/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/dist.py", line 30, in <module>
        from setuptools.depends import Require
      File "/home/mf/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/mf/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mf/.pyenv/versions/3.9.5/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hkvk21ac/pynndescent_580104e55fcd428a8187c7566ef5b0a0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hkvk21ac/pynndescent_580104e55fcd428a8187c7566ef5b0a0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nsj8ft48/install-record.txt --single-version-externally-managed --compile --install-headers /home/mf/.pyenv/versions/3.9.5/include/python3.9/pynndescent Check the logs for full command output.
```

related problem seems to be: https://github.com/coursera-dl/coursera-dl/issues/778 

thanks
Mark

**Comment by molindoudou** [comment]
It's successfully installed when I run 
`conda create -n py39 python=3.9.5`
`conda activate py39`
`pip install stereopy`
in a centos operating system.maybe you can try on my way to see if it's the difference of conda environment or operating system cause this proplem.

**Comment by fuyawangye** [comment]
take
