### ISSUE TITLE
Error in data.tl.leiden

### ISSUE THREAD

**Issue by lh12565** [BGIResearch/stereopy#97]
Hi, when I run 'data.tl.leiden(neighbors_res_key='neighbors', res_key='leiden')', there is an error below:
```python
data.tl.filter_cells(min_gene=200, pct_counts_mt=10, min_n_genes_by_counts=3, inplace=True)
data.tl.filter_genes(min_cell=10)
data.tl.raw_checkpoint()
data.tl.normalize_total(target_sum=10000)
data.tl.log1p()
data.tl.highly_variable_genes(min_mean=0.0125, max_mean=3,min_disp=0.5,
                              n_top_genes=2000, res_key='highly_variable_genes')
data.tl.scale(max_value=10, zero_center=True)
data.tl.pca(use_highly_genes=False, n_pcs=50, res_key='pca')
data.tl.neighbors(pca_res_key='pca', n_pcs=50, res_key='neighbors')
data.tl.umap(pca_res_key='pca', neighbors_res_key='neighbors', res_key='umap')
data.tl.leiden(neighbors_res_key='neighbors', res_key='leiden')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/NAS/lh/software/miniconda3/envs/st/lib/python3.8/site-packages/stereopy-0.9.0-py3.8.egg/stereo/core/st_pipeline.py", line 34, in wrapped
    res = func(*args, **kwargs)
  File "/NAS/lh/software/miniconda3/envs/st/lib/python3.8/site-packages/stereopy-0.9.0-py3.8.egg/stereo/core/st_pipeline.py", line 590, in leiden
    clusters = le(neighbor=neighbor, adjacency=connectivities, directed=directed, resolution=resolution,
  File "/NAS/lh/software/miniconda3/envs/st/lib/python3.8/site-packages/stereopy-0.9.0-py3.8.egg/stereo/algorithm/leiden.py", line 89, in leiden
    part = leidenalg.find_partition(g, partition_type, **partition_kwargs)
  File "/NAS/lh/software/miniconda3/envs/st/lib/python3.8/site-packages/leidenalg/functions.py", line 81, in find_partition
    partition = partition_type(graph,
  File "/NAS/lh/software/miniconda3/envs/st/lib/python3.8/site-packages/leidenalg/VertexPartition.py", line 840, in __init__
    self._partition = _c_leiden._new_RBConfigurationVertexPartition(pygraph_t,
BaseException: Could not construct partition: Weight vector not the same size as the number of edges.
```

I don't know how to solve it? Thanks!

**Comment by LyonLen** [comment]
Hi~Could you please show us your python site-packages version using the `pip list`?

**Comment by lh12565** [comment]
> Hi~Could you please show us your python site-packages version using the `pip list`?

Thanks, I reinstall the stereopy and it works.

**Comment by LyonLen** [comment]
Nice. But if you need further help, you can reopen the issue.

**Comment by lvmt** [comment]
@LyonLen  你好，我在运行`data.tl.leiden(neighbors_res_key='neighbors', res_key='leiden')`也遇到了相同的错误，此时stereo的版本是0.11.0,； 

后续我将stereo回退到0.10.0，则程序可以正常运行。希望你们能对后续版本中的问题进行debug。谢谢。
